# Generated by Django 2.0.6 on 2018-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='tree_deep',
            field=models.PositiveSmallIntegerField(default=13),
        ),
    ]
