# Generated by Django 2.0.6 on 2018-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_tree_deep'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='pages_paginator',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Количество записей для пагинатора'),
        ),
    ]
