# Generated by Django 2.0.6 on 2018-06-28 16:31

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryPointsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_points', models.IntegerField(verbose_name='Баллы')),
                ('right_points', models.IntegerField(verbose_name='Баллы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'История начисления и списания баллов',
                'verbose_name_plural': 'История начисления и списания баллов',
            },
        ),
        migrations.CreateModel(
            name='BinaryTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, unique=True, verbose_name='Пользователь')),
                ('left_node', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Левый ребёнок')),
                ('right_node', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Правый ребёнок')),
                ('left_points', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Баллы в левой ноге')),
                ('right_points', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Баллы в правой ноге')),
                ('status', models.CharField(choices=[('1', 'Неактивный'), ('2', 'Активный'), ('3', 'Заморожен'), ('4', 'Полное заполнение')], default='1', max_length=1, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.BinaryTree', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Бинарное дерево',
                'verbose_name_plural': 'Бинарные деревья',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Основание для начисления или списания баллов',
                'verbose_name_plural': 'Основания для начисления или списания баллов',
            },
        ),
        migrations.AddField(
            model_name='binarypointshistory',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.Reason'),
        ),
        migrations.AddField(
            model_name='binarypointshistory',
            name='tree_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.BinaryTree', verbose_name='Пользователь'),
        ),
    ]
