# Generated by Django 2.0.6 on 2018-07-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='code',
            field=models.PositiveSmallIntegerField(default=1101),
            preserve_default=False,
        ),
    ]
