# Generated by Django 2.0.6 on 2018-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_reason_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarypointshistory',
            name='left_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='binarypointshistory',
            name='right_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баллы'),
        ),
    ]
