# Generated by Django 2.0.6 on 2018-07-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20180702_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
